//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use pumpfun_program_sdk::accounts::BondingCurve;
use pumpfun_program_sdk::accounts::Global;
use pumpfun_program_sdk::ID;

/// Pumpfun Program State
#[allow(clippy::large_enum_variant)]
#[derive(Debug)]
pub enum PumpfunProgramState {
    Global(Global),
    BondingCurve(BondingCurve),
}

impl PumpfunProgramState {
    pub fn try_unpack(data_bytes: &[u8]) -> yellowstone_vixen_core::ParseResult<Self> {
        let data_len = data_bytes.len();
        const GLOBAL_LEN: usize = std::mem::size_of::<Global>();
        const BONDINGCURVE_LEN: usize = std::mem::size_of::<BondingCurve>();
        match data_len {
            GLOBAL_LEN => Ok(PumpfunProgramState::Global(Global::from_bytes(data_bytes)?)),
            BONDINGCURVE_LEN => Ok(PumpfunProgramState::BondingCurve(BondingCurve::from_bytes(
                data_bytes,
            )?)),
            _ => Err(yellowstone_vixen_core::ParseError::from(
                "Invalid Account data length".to_owned(),
            )),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub struct AccountParser;

impl yellowstone_vixen_core::Parser for AccountParser {
    type Input = yellowstone_vixen_core::AccountUpdate;
    type Output = PumpfunProgramState;

    fn id(&self) -> std::borrow::Cow<str> {
        "pumpfun::AccountParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .account_owners([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        acct: &yellowstone_vixen_core::AccountUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        let inner = acct
            .account
            .as_ref()
            .ok_or(solana_program::program_error::ProgramError::InvalidArgument)?;
        PumpfunProgramState::try_unpack(&inner.data)
    }
}

impl yellowstone_vixen_core::ProgramParser for AccountParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}
