//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use pumpfun_program_sdk::instructions::{
    Buy as BuyIxAccounts, BuyInstructionArgs as BuyIxData, Create as CreateIxAccounts,
    CreateInstructionArgs as CreateIxData, Initialize as InitializeIxAccounts,
    Sell as SellIxAccounts, SellInstructionArgs as SellIxData, SetParams as SetParamsIxAccounts,
    SetParamsInstructionArgs as SetParamsIxData, Withdraw as WithdrawIxAccounts,
};
use pumpfun_program_sdk::types::{CompleteEvent, CreateEvent, SetParamsEvent, TradeEvent};
use pumpfun_program_sdk::ID;

use solana_program::pubkey::Pubkey;

/// Pumpfun Instructions
#[derive(Debug)]
pub enum PumpfunProgramIx {
    Initialize(InitializeIxAccounts),
    SetParams(SetParamsIxAccounts, SetParamsIxData),
    Create(CreateIxAccounts, CreateIxData),
    Buy(BuyIxAccounts, BuyIxData),
    Sell(SellIxAccounts, SellIxData),
    Withdraw(WithdrawIxAccounts),
    TradeEvent(TradeEvent),
    CreateEvent(CreateEvent),
    CompleteEvent(CompleteEvent),
    SetParamsEvent(SetParamsEvent),
}

#[derive(Debug, Copy, Clone)]
pub struct InstructionParser;

impl yellowstone_vixen_core::Parser for InstructionParser {
    type Input = yellowstone_vixen_core::instruction::InstructionUpdate;
    type Output = PumpfunProgramIx;

    fn id(&self) -> std::borrow::Cow<str> {
        "Pumpfun::InstructionParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .transaction_accounts([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        ix_update: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        if ix_update.program.equals_ref(ID) {
            InstructionParser::parse_impl(ix_update)
        } else {
            Err(yellowstone_vixen_core::ParseError::Filtered)
        }
    }
}

impl yellowstone_vixen_core::ProgramParser for InstructionParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

impl InstructionParser {
    pub(crate) fn parse_impl(
        ix: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<PumpfunProgramIx> {
        let accounts_len = ix.accounts.len();
        let ix_discriminator: [u8; 8] = ix.data[0..8].try_into()?;
        let mut ix_data = &ix.data[8..];
        match ix_discriminator {
            [175, 175, 109, 31, 13, 152, 155, 237] => {
                check_min_accounts_req(accounts_len, 3)?;
                let ix_accounts = InitializeIxAccounts {
                    global: ix.accounts[0].0.into(),
                    user: ix.accounts[1].0.into(),
                    system_program: ix.accounts[2].0.into(),
                };
                Ok(PumpfunProgramIx::Initialize(ix_accounts))
            },
            [27, 234, 178, 52, 147, 2, 187, 141] => {
                check_min_accounts_req(accounts_len, 5)?;
                let ix_accounts = SetParamsIxAccounts {
                    global: ix.accounts[0].0.into(),
                    user: ix.accounts[1].0.into(),
                    system_program: ix.accounts[2].0.into(),
                    event_authority: ix.accounts[3].0.into(),
                    program: ix.accounts[4].0.into(),
                };
                let de_ix_data: SetParamsIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(PumpfunProgramIx::SetParams(ix_accounts, de_ix_data))
            },
            [24, 30, 200, 40, 5, 28, 7, 119] => {
                check_min_accounts_req(accounts_len, 14)?;
                let ix_accounts = CreateIxAccounts {
                    mint: ix.accounts[0].0.into(),
                    mint_authority: ix.accounts[1].0.into(),
                    bonding_curve: ix.accounts[2].0.into(),
                    associated_bonding_curve: ix.accounts[3].0.into(),
                    global: ix.accounts[4].0.into(),
                    mpl_token_metadata: ix.accounts[5].0.into(),
                    metadata: ix.accounts[6].0.into(),
                    user: ix.accounts[7].0.into(),
                    system_program: ix.accounts[8].0.into(),
                    token_program: ix.accounts[9].0.into(),
                    associated_token_program: ix.accounts[10].0.into(),
                    rent: ix.accounts[11].0.into(),
                    event_authority: ix.accounts[12].0.into(),
                    program: ix.accounts[13].0.into(),
                };
                let de_ix_data: CreateIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(PumpfunProgramIx::Create(ix_accounts, de_ix_data))
            },
            [102, 6, 61, 18, 1, 218, 235, 234] => {
                check_min_accounts_req(accounts_len, 12)?;
                let ix_accounts = BuyIxAccounts {
                    global: ix.accounts[0].0.into(),
                    fee_recipient: ix.accounts[1].0.into(),
                    mint: ix.accounts[2].0.into(),
                    bonding_curve: ix.accounts[3].0.into(),
                    associated_bonding_curve: ix.accounts[4].0.into(),
                    associated_user: ix.accounts[5].0.into(),
                    user: ix.accounts[6].0.into(),
                    system_program: ix.accounts[7].0.into(),
                    token_program: ix.accounts[8].0.into(),
                    rent: ix.accounts[9].0.into(),
                    event_authority: ix.accounts[10].0.into(),
                    program: ix.accounts[11].0.into(),
                };
                let de_ix_data: BuyIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(PumpfunProgramIx::Buy(ix_accounts, de_ix_data))
            },
            [51, 230, 133, 164, 1, 127, 131, 173] => {
                check_min_accounts_req(accounts_len, 12)?;
                let ix_accounts = SellIxAccounts {
                    global: ix.accounts[0].0.into(),
                    fee_recipient: ix.accounts[1].0.into(),
                    mint: ix.accounts[2].0.into(),
                    bonding_curve: ix.accounts[3].0.into(),
                    associated_bonding_curve: ix.accounts[4].0.into(),
                    associated_user: ix.accounts[5].0.into(),
                    user: ix.accounts[6].0.into(),
                    system_program: ix.accounts[7].0.into(),
                    associated_token_program: ix.accounts[8].0.into(),
                    token_program: ix.accounts[9].0.into(),
                    event_authority: ix.accounts[10].0.into(),
                    program: ix.accounts[11].0.into(),
                };
                let de_ix_data: SellIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(PumpfunProgramIx::Sell(ix_accounts, de_ix_data))
            },
            [183, 18, 70, 156, 148, 109, 161, 34] => {
                check_min_accounts_req(accounts_len, 11)?;
                let ix_accounts = WithdrawIxAccounts {
                    global: ix.accounts[0].0.into(),
                    mint: ix.accounts[1].0.into(),
                    bonding_curve: ix.accounts[2].0.into(),
                    associated_bonding_curve: ix.accounts[3].0.into(),
                    associated_user: ix.accounts[4].0.into(),
                    user: ix.accounts[5].0.into(),
                    system_program: ix.accounts[6].0.into(),
                    token_program: ix.accounts[7].0.into(),
                    rent: ix.accounts[8].0.into(),
                    event_authority: ix.accounts[9].0.into(),
                    program: ix.accounts[10].0.into(),
                };
                Ok(PumpfunProgramIx::Withdraw(ix_accounts))
            },
            [228, 69, 165, 46, 81, 203, 154, 29] => {
                let event_descriminator: [u8; 8] = ix.data[8..16].try_into()?;
                let mut event_data = &ix.data[16..];
                match event_descriminator {
                    [27, 114, 169, 77, 222, 235, 99, 118] => {
                        let de_ix_data: CreateEvent =
                            BorshDeserialize::deserialize(&mut event_data)?;
                        Ok(PumpfunProgramIx::CreateEvent(de_ix_data))
                    },
                    [189, 219, 127, 211, 78, 230, 97, 238] => {
                        let de_ix_data: TradeEvent =
                            BorshDeserialize::deserialize(&mut event_data)?;
                        Ok(PumpfunProgramIx::TradeEvent(de_ix_data))
                    },
                    _ => {
                        // println!(
                        //     "Transaction signature: {:?}",
                        //     bs58::encode(ix.shared.signature.clone()).into_string(),
                        // );
                        // println!("Event discriminator: {:?}", event_descriminator);
                        Err(yellowstone_vixen_core::ParseError::from(
                            "Invalid Instruction discriminator".to_owned(),
                        ))
                    },
                }
            },
            _ => Err(yellowstone_vixen_core::ParseError::from(
                "Invalid Instruction discriminator".to_owned(),
            )),
        }
    }
}

pub fn check_min_accounts_req(
    actual: usize,
    expected: usize,
) -> yellowstone_vixen_core::ParseResult<()> {
    if actual < expected {
        Err(yellowstone_vixen_core::ParseError::from(format!(
            "Too few accounts provided: expected {expected}, got {actual}"
        )))
    } else {
        Ok(())
    }
}

#[cfg(feature = "proto")]
mod proto_parser {
    use pumpfun_program_sdk::ID;
    use yellowstone_vixen_core::proto::ParseProto;
    use yellowstone_vixen_proto::parser::{
        pumpfun_program_ix_proto::IxOneof, PumpfunBuyAccountsProto, PumpfunBuyInstructionProto,
        PumpfunBuyIxDataProto, PumpfunCreateEventProto, PumpfunProgramIxProto,
        PumpfunSellAccountsProto, PumpfunSellInstructionProto, PumpfunSellIxDataProto,
        PumpfunTradeEventProto,
    };

    use super::{
        BuyIxAccounts, BuyIxData, CreateEvent, InstructionParser, PumpfunProgramIx, SellIxAccounts,
        SellIxData, TradeEvent,
    };
    use crate::helpers::IntoProto;

    impl ParseProto for InstructionParser {
        type Message = PumpfunProgramIxProto;

        fn output_into_message(value: Self::Output) -> Self::Message {
            value.into_proto()
        }
    }

    impl IntoProto<PumpfunBuyAccountsProto> for BuyIxAccounts {
        fn into_proto(self) -> PumpfunBuyAccountsProto {
            PumpfunBuyAccountsProto {
                global: self.global.to_string(),
                fee_recipient: self.fee_recipient.to_string(),
                mint: self.mint.to_string(),
                bonding_curve: self.bonding_curve.to_string(),
                associated_bonding_curve: self.associated_bonding_curve.to_string(),
                associated_user: self.associated_user.to_string(),
                user: self.user.to_string(),
                system_program: self.system_program.to_string(),
                token_program: self.token_program.to_string(),
                rent: self.rent.to_string(),
                event_authority: self.event_authority.to_string(),
                program: self.program.to_string(),
            }
        }
    }

    impl IntoProto<PumpfunBuyIxDataProto> for BuyIxData {
        fn into_proto(self) -> PumpfunBuyIxDataProto {
            PumpfunBuyIxDataProto {
                amount: self.amount,
                max_sol_cost: self.max_sol_cost,
            }
        }
    }

    impl IntoProto<PumpfunCreateEventProto> for CreateEvent {
        fn into_proto(self) -> PumpfunCreateEventProto {
            PumpfunCreateEventProto {
                name: self.name,
                symbol: self.symbol,
                uri: self.uri,
                mint: self.mint.to_string(),
                bonding_curve: self.bonding_curve.to_string(),
                user: self.user.to_string(),
            }
        }
    }

    impl IntoProto<PumpfunTradeEventProto> for TradeEvent {
        fn into_proto(self) -> PumpfunTradeEventProto {
            PumpfunTradeEventProto {
                mint: self.mint.to_string(),
                sol_amount: self.sol_amount,
                token_amount: self.token_amount,
                is_buy: self.is_buy,
                user: self.user.to_string(),
                timestamp: self.timestamp,
                virtual_sol_reserves: self.virtual_sol_reserves,
                virtual_token_reserves: self.virtual_token_reserves,
            }
        }
    }

    impl IntoProto<PumpfunSellAccountsProto> for SellIxAccounts {
        fn into_proto(self) -> PumpfunSellAccountsProto {
            PumpfunSellAccountsProto {
                global: self.global.to_string(),
                fee_recipient: self.fee_recipient.to_string(),
                mint: self.mint.to_string(),
                bonding_curve: self.bonding_curve.to_string(),
                associated_bonding_curve: self.associated_bonding_curve.to_string(),
                associated_user: self.associated_user.to_string(),
                user: self.user.to_string(),
                system_program: self.system_program.to_string(),
                associated_token_program: self.associated_token_program.to_string(),
                token_program: self.token_program.to_string(),
                event_authority: self.event_authority.to_string(),
                program: self.program.to_string(),
            }
        }
    }

    impl IntoProto<PumpfunSellIxDataProto> for SellIxData {
        fn into_proto(self) -> PumpfunSellIxDataProto {
            PumpfunSellIxDataProto {
                amount: self.amount,
                min_sol_output: self.min_sol_output,
            }
        }
    }

    impl IntoProto<PumpfunProgramIxProto> for PumpfunProgramIx {
        fn into_proto(self) -> PumpfunProgramIxProto {
            match self {
                PumpfunProgramIx::Buy(accounts, data) => PumpfunProgramIxProto {
                    ix_oneof: Some(IxOneof::Buy(PumpfunBuyInstructionProto {
                        accounts: Some(accounts.into_proto()),
                        data: Some(data.into_proto()),
                    })),
                },
                PumpfunProgramIx::Sell(accounts, data) => PumpfunProgramIxProto {
                    ix_oneof: Some(IxOneof::Sell(PumpfunSellInstructionProto {
                        accounts: Some(accounts.into_proto()),
                        data: Some(data.into_proto()),
                    })),
                },
                PumpfunProgramIx::CreateEvent(data) => PumpfunProgramIxProto {
                    ix_oneof: Some(IxOneof::CreateEvent(data.into_proto())),
                },
                PumpfunProgramIx::TradeEvent(data) => PumpfunProgramIxProto {
                    ix_oneof: Some(IxOneof::TradeEvent(data.into_proto())),
                },
                //Ingore others
                _ => PumpfunProgramIxProto { ix_oneof: None },
            }
        }
    }
}
