//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use jupiter_program_sdk::accounts::TokenLedger;
use jupiter_program_sdk::ID;


/// Jupiter Program State
#[allow(clippy::large_enum_variant)]
#[derive(Debug)]
pub enum JupiterProgramState {
            TokenLedger(TokenLedger),
    }

impl JupiterProgramState {
    pub fn try_unpack(data_bytes:&[u8]) -> yellowstone_vixen_core::ParseResult<Self>{
        let data_len = data_bytes.len();    
                                    const TOKENLEDGER_LEN:usize = std::mem::size_of::<TokenLedger>();
                            match data_len {
                                    TOKENLEDGER_LEN => Ok(
                    JupiterProgramState::TokenLedger(
                        TokenLedger::from_bytes(data_bytes)?
                    )
                    ),
                            _ => Err(yellowstone_vixen_core::ParseError::from("Invalid Account data length".to_owned())),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub struct AccountParser;

impl yellowstone_vixen_core::Parser for AccountParser {
    type Input = yellowstone_vixen_core::AccountUpdate;
    type Output = JupiterProgramState;

    fn id(&self) -> std::borrow::Cow<str> {
        "jupiter::AccountParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .account_owners([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        acct: &yellowstone_vixen_core::AccountUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        let inner = acct.account.as_ref().ok_or(solana_program::program_error::ProgramError::InvalidArgument)?;
           JupiterProgramState::try_unpack(&inner.data)
    }
}

impl yellowstone_vixen_core::ProgramParser for AccountParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

#[cfg(feature = "proto")]
mod proto_parser {
    use yellowstone_vixen_core::proto::ParseProto;
    use yellowstone_vixen_proto::parser::{
        jupiter_program_state_proto, JupiterProgramStateProto, TokenLedgerProto,
    };

    use super::{
        AccountParser, JupiterProgramState, TokenLedger
    };
    use crate::helpers::IntoProto;

    impl IntoProto<TokenLedgerProto> for TokenLedger {
        fn into_proto(self) -> TokenLedgerProto {
            TokenLedgerProto {
                discriminator: self.discriminator.to_vec(),
                token_account: self.token_account.to_string(),
                amount: self.amount,
            }
        }
    }
    impl ParseProto for AccountParser {
        type Message = JupiterProgramStateProto;

        fn output_into_message(value: Self::Output) -> Self::Message {
            let state_oneof = match value {
                JupiterProgramState::TokenLedger(data) => Some(
                    jupiter_program_state_proto::StateOneof::TokenLedger(data.into_proto()),
                ),
            };
            Self::Message { state_oneof }
        }
    }
}
