//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use jupiter_program_sdk::instructions::{
    Claim as ClaimIxAccounts, ClaimInstructionArgs as ClaimIxData,
    ClaimToken as ClaimTokenIxAccounts, ClaimTokenInstructionArgs as ClaimTokenIxData,
    CreateOpenOrders as CreateOpenOrdersIxAccounts,
    CreateProgramOpenOrders as CreateProgramOpenOrdersIxAccounts,
    CreateProgramOpenOrdersInstructionArgs as CreateProgramOpenOrdersIxData,
    CreateTokenAccount as CreateTokenAccountIxAccounts,
    CreateTokenAccountInstructionArgs as CreateTokenAccountIxData,
    CreateTokenLedger as CreateTokenLedgerIxAccounts, ExactOutRoute as ExactOutRouteIxAccounts,
    ExactOutRouteInstructionArgs as ExactOutRouteIxData, Route as RouteIxAccounts,
    RouteInstructionArgs as RouteIxData, RouteWithTokenLedger as RouteWithTokenLedgerIxAccounts,
    RouteWithTokenLedgerInstructionArgs as RouteWithTokenLedgerIxData,
    SetTokenLedger as SetTokenLedgerIxAccounts,
    SharedAccountsExactOutRoute as SharedAccountsExactOutRouteIxAccounts,
    SharedAccountsExactOutRouteInstructionArgs as SharedAccountsExactOutRouteIxData,
    SharedAccountsRoute as SharedAccountsRouteIxAccounts,
    SharedAccountsRouteInstructionArgs as SharedAccountsRouteIxData,
    SharedAccountsRouteWithTokenLedger as SharedAccountsRouteWithTokenLedgerIxAccounts,
    SharedAccountsRouteWithTokenLedgerInstructionArgs as SharedAccountsRouteWithTokenLedgerIxData,
};
use jupiter_program_sdk::types::{FeeEvent, SwapEvent};
use jupiter_program_sdk::ID;
use solana_program::pubkey::Pubkey;
use yellowstone_vixen_core::instruction::InstructionUpdate;

/// Jupiter Instructions
#[derive(Debug)]
pub enum JupiterProgramIx {
    Route(RouteIxAccounts, RouteIxData),
    RouteWithTokenLedger(RouteWithTokenLedgerIxAccounts, RouteWithTokenLedgerIxData),
    SharedAccountsRoute(SharedAccountsRouteIxAccounts, SharedAccountsRouteIxData),
    SharedAccountsRouteWithTokenLedger(
        SharedAccountsRouteWithTokenLedgerIxAccounts,
        SharedAccountsRouteWithTokenLedgerIxData,
    ),
    ExactOutRoute(ExactOutRouteIxAccounts, ExactOutRouteIxData),
    SharedAccountsExactOutRoute(
        SharedAccountsExactOutRouteIxAccounts,
        SharedAccountsExactOutRouteIxData,
    ),
    SetTokenLedger(SetTokenLedgerIxAccounts),
    CreateOpenOrders(CreateOpenOrdersIxAccounts),
    CreateTokenAccount(CreateTokenAccountIxAccounts, CreateTokenAccountIxData),
    CreateProgramOpenOrders(
        CreateProgramOpenOrdersIxAccounts,
        CreateProgramOpenOrdersIxData,
    ),
    Claim(ClaimIxAccounts, ClaimIxData),
    ClaimToken(ClaimTokenIxAccounts, ClaimTokenIxData),
    CreateTokenLedger(CreateTokenLedgerIxAccounts),
    SwapEvent(SwapEvent),
    FeeEvent(FeeEvent),
}

#[derive(Debug, Copy, Clone)]
pub struct InstructionParser;

impl yellowstone_vixen_core::Parser for InstructionParser {
    type Input = yellowstone_vixen_core::instruction::InstructionUpdate;
    type Output = JupiterProgramIx;

    fn id(&self) -> std::borrow::Cow<str> {
        "Jupiter::InstructionParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .transaction_accounts([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        ix_update: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        if ix_update.program.equals_ref(ID) {
            InstructionParser::parse_impl(ix_update)
        } else {
            Err(yellowstone_vixen_core::ParseError::Filtered)
        }
    }
}

impl yellowstone_vixen_core::ProgramParser for InstructionParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

impl InstructionParser {
    pub(crate) fn parse_impl(
        ix: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<JupiterProgramIx> {
        let accounts_len = ix.accounts.len();
        let ix_discriminator: [u8; 8] = ix.data[0..8].try_into()?;
        let mut ix_data = &ix.data[8..];

        match ix_discriminator {
            [229, 23, 203, 151, 122, 227, 173, 42] => {
                check_min_accounts_req(accounts_len, 7)?;
                let ix_accounts = RouteIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    user_transfer_authority: ix.accounts[1].0.into(),
                    user_source_token_account: ix.accounts[2].0.into(),
                    user_destination_token_account: ix.accounts[3].0.into(),
                    destination_token_account: Some(Pubkey::new_from_array(ix.accounts[4].0)),
                    destination_mint: ix.accounts[5].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[6].0)),
                };
                let de_ix_data: RouteIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::Route(ix_accounts, de_ix_data))
            },
            [150, 86, 71, 116, 167, 93, 14, 104] => {
                check_min_accounts_req(accounts_len, 8)?;
                let ix_accounts = RouteWithTokenLedgerIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    user_transfer_authority: ix.accounts[1].0.into(),
                    user_source_token_account: ix.accounts[2].0.into(),
                    user_destination_token_account: ix.accounts[3].0.into(),
                    destination_token_account: Some(Pubkey::new_from_array(ix.accounts[4].0)),
                    destination_mint: ix.accounts[5].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[6].0)),
                    token_ledger: ix.accounts[7].0.into(),
                };
                let de_ix_data: RouteWithTokenLedgerIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::RouteWithTokenLedger(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [193, 32, 155, 51, 65, 214, 156, 129] => {
                check_min_accounts_req(accounts_len, 11)?;
                let ix_accounts = SharedAccountsRouteIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    program_authority: ix.accounts[1].0.into(),
                    user_transfer_authority: ix.accounts[2].0.into(),
                    source_token_account: ix.accounts[3].0.into(),
                    program_source_token_account: ix.accounts[4].0.into(),
                    program_destination_token_account: ix.accounts[5].0.into(),
                    destination_token_account: ix.accounts[6].0.into(),
                    source_mint: ix.accounts[7].0.into(),
                    destination_mint: ix.accounts[8].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[9].0)),
                    token2022_program: Some(Pubkey::new_from_array(ix.accounts[10].0)),
                };
                let de_ix_data: SharedAccountsRouteIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::SharedAccountsRoute(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [230, 121, 143, 80, 119, 159, 106, 170] => {
                check_min_accounts_req(accounts_len, 12)?;
                let ix_accounts = SharedAccountsRouteWithTokenLedgerIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    program_authority: ix.accounts[1].0.into(),
                    user_transfer_authority: ix.accounts[2].0.into(),
                    source_token_account: ix.accounts[3].0.into(),
                    program_source_token_account: ix.accounts[4].0.into(),
                    program_destination_token_account: ix.accounts[5].0.into(),
                    destination_token_account: ix.accounts[6].0.into(),
                    source_mint: ix.accounts[7].0.into(),
                    destination_mint: ix.accounts[8].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[9].0)),
                    token2022_program: Some(Pubkey::new_from_array(ix.accounts[10].0)),
                    token_ledger: ix.accounts[11].0.into(),
                };
                let de_ix_data: SharedAccountsRouteWithTokenLedgerIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::SharedAccountsRouteWithTokenLedger(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [208, 51, 239, 151, 123, 43, 237, 92] => {
                check_min_accounts_req(accounts_len, 9)?;
                let ix_accounts = ExactOutRouteIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    user_transfer_authority: ix.accounts[1].0.into(),
                    user_source_token_account: ix.accounts[2].0.into(),
                    user_destination_token_account: ix.accounts[3].0.into(),
                    destination_token_account: Some(Pubkey::new_from_array(ix.accounts[4].0)),
                    source_mint: ix.accounts[5].0.into(),
                    destination_mint: ix.accounts[6].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[7].0)),
                    token2022_program: Some(Pubkey::new_from_array(ix.accounts[8].0)),
                };
                let de_ix_data: ExactOutRouteIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::ExactOutRoute(ix_accounts, de_ix_data))
            },
            [176, 209, 105, 168, 154, 125, 69, 62] => {
                check_min_accounts_req(accounts_len, 11)?;
                let ix_accounts = SharedAccountsExactOutRouteIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    program_authority: ix.accounts[1].0.into(),
                    user_transfer_authority: ix.accounts[2].0.into(),
                    source_token_account: ix.accounts[3].0.into(),
                    program_source_token_account: ix.accounts[4].0.into(),
                    program_destination_token_account: ix.accounts[5].0.into(),
                    destination_token_account: ix.accounts[6].0.into(),
                    source_mint: ix.accounts[7].0.into(),
                    destination_mint: ix.accounts[8].0.into(),
                    platform_fee_account: Some(Pubkey::new_from_array(ix.accounts[9].0)),
                    token2022_program: Some(Pubkey::new_from_array(ix.accounts[10].0)),
                };
                let de_ix_data: SharedAccountsExactOutRouteIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::SharedAccountsExactOutRoute(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [228, 85, 185, 112, 78, 79, 77, 2] => {
                check_min_accounts_req(accounts_len, 2)?;
                let ix_accounts = SetTokenLedgerIxAccounts {
                    token_ledger: ix.accounts[0].0.into(),
                    token_account: ix.accounts[1].0.into(),
                };
                Ok(JupiterProgramIx::SetTokenLedger(ix_accounts))
            },
            [229, 194, 212, 172, 8, 10, 134, 147] => {
                check_min_accounts_req(accounts_len, 6)?;
                let ix_accounts = CreateOpenOrdersIxAccounts {
                    open_orders: ix.accounts[0].0.into(),
                    payer: ix.accounts[1].0.into(),
                    dex_program: ix.accounts[2].0.into(),
                    system_program: ix.accounts[3].0.into(),
                    rent: ix.accounts[4].0.into(),
                    market: ix.accounts[5].0.into(),
                };
                Ok(JupiterProgramIx::CreateOpenOrders(ix_accounts))
            },
            [147, 241, 123, 100, 244, 132, 174, 118] => {
                check_min_accounts_req(accounts_len, 5)?;
                let ix_accounts = CreateTokenAccountIxAccounts {
                    token_account: ix.accounts[0].0.into(),
                    user: ix.accounts[1].0.into(),
                    mint: ix.accounts[2].0.into(),
                    token_program: ix.accounts[3].0.into(),
                    system_program: ix.accounts[4].0.into(),
                };
                let de_ix_data: CreateTokenAccountIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::CreateTokenAccount(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [28, 226, 32, 148, 188, 136, 113, 171] => {
                check_min_accounts_req(accounts_len, 7)?;
                let ix_accounts = CreateProgramOpenOrdersIxAccounts {
                    open_orders: ix.accounts[0].0.into(),
                    payer: ix.accounts[1].0.into(),
                    program_authority: ix.accounts[2].0.into(),
                    dex_program: ix.accounts[3].0.into(),
                    system_program: ix.accounts[4].0.into(),
                    rent: ix.accounts[5].0.into(),
                    market: ix.accounts[6].0.into(),
                };
                let de_ix_data: CreateProgramOpenOrdersIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::CreateProgramOpenOrders(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [62, 198, 214, 193, 213, 159, 108, 210] => {
                check_min_accounts_req(accounts_len, 3)?;
                let ix_accounts = ClaimIxAccounts {
                    wallet: ix.accounts[0].0.into(),
                    program_authority: ix.accounts[1].0.into(),
                    system_program: ix.accounts[2].0.into(),
                };
                let de_ix_data: ClaimIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::Claim(ix_accounts, de_ix_data))
            },
            [116, 206, 27, 191, 166, 19, 0, 73] => {
                check_min_accounts_req(accounts_len, 9)?;
                let ix_accounts = ClaimTokenIxAccounts {
                    payer: ix.accounts[0].0.into(),
                    wallet: ix.accounts[1].0.into(),
                    program_authority: ix.accounts[2].0.into(),
                    program_token_account: ix.accounts[3].0.into(),
                    destination_token_account: ix.accounts[4].0.into(),
                    mint: ix.accounts[5].0.into(),
                    associated_token_token_program: ix.accounts[6].0.into(),
                    associated_token_program: ix.accounts[7].0.into(),
                    system_program: ix.accounts[8].0.into(),
                };
                let de_ix_data: ClaimTokenIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(JupiterProgramIx::ClaimToken(ix_accounts, de_ix_data))
            },
            [232, 242, 197, 253, 240, 143, 129, 52] => {
                check_min_accounts_req(accounts_len, 3)?;
                let ix_accounts = CreateTokenLedgerIxAccounts {
                    token_ledger: ix.accounts[0].0.into(),
                    payer: ix.accounts[1].0.into(),
                    system_program: ix.accounts[2].0.into(),
                };
                Ok(JupiterProgramIx::CreateTokenLedger(ix_accounts))
            },
            [228, 69, 165, 46, 81, 203, 154, 29] => {
                let event_descriminator: [u8; 8] = ix.data[8..16].try_into()?;
                match event_descriminator {
                    [73, 79, 78, 127, 184, 213, 13, 220] => {
                        let de_ix_data: FeeEvent = BorshDeserialize::deserialize(&mut ix_data)?;
                        Ok(JupiterProgramIx::FeeEvent(de_ix_data))
                    },
                    [64, 198, 205, 232, 38, 8, 113, 226] => {
                        let de_ix_data: SwapEvent = BorshDeserialize::deserialize(&mut ix_data)?;
                        Ok(JupiterProgramIx::SwapEvent(de_ix_data))
                    },
                    _ => {
                        return Err(yellowstone_vixen_core::ParseError::from(
                            "Invalid Instruction discriminator".to_owned(),
                        ));
                    },
                }
            },
            _ => {
                println!("Instruction discriminator: {:?}", ix.data);
                Err(yellowstone_vixen_core::ParseError::from(
                    "Invalid Instruction discriminator".to_owned(),
                ))
            },
        }
    }
}

pub fn check_min_accounts_req(
    actual: usize,
    expected: usize,
) -> yellowstone_vixen_core::ParseResult<()> {
    if actual < expected {
        Err(yellowstone_vixen_core::ParseError::from(format!(
            "Too few accounts provided: expected {expected}, got {actual}"
        )))
    } else {
        Ok(())
    }
}

#[cfg(feature = "proto")]
mod proto_parser {
    use jupiter_program_sdk::{types::RoutePlanStep, ID};
    use yellowstone_vixen_core::proto::ParseProto;
    use yellowstone_vixen_proto::parser::{
        jupiter_program_ix_proto::IxOneof, JupiterProgramIxProto, JupiterRouteAccountsProto,
        JupiterRouteInstructionProto, JupiterRouteIxDataProto, JupiterRoutePlanStepProto,
        JupiterSwapEventProto,
    };

    use super::{InstructionParser, JupiterProgramIx, RouteIxAccounts, RouteIxData, SwapEvent};
    use crate::helpers::IntoProto;

    impl IntoProto<JupiterRouteAccountsProto> for RouteIxAccounts {
        fn into_proto(self) -> JupiterRouteAccountsProto {
            JupiterRouteAccountsProto {
                token_program: self.token_program.to_string(),
                user_transfer_authority: self.user_transfer_authority.to_string(),
                user_source_token_account: self.user_source_token_account.to_string(),
                user_destination_token_account: self.user_destination_token_account.to_string(),
                destination_token_account: self.destination_token_account.unwrap_or(ID).to_string(),
                destination_mint: self.destination_mint.to_string(),
                platform_fee_account: self.platform_fee_account.unwrap_or(ID).to_string(),
            }
        }
    }

    impl IntoProto<JupiterRoutePlanStepProto> for RoutePlanStep {
        fn into_proto(self) -> JupiterRoutePlanStepProto {
            JupiterRoutePlanStepProto {
                swap: format!("{:?}", self.swap),
                percent: self.percent as u64,
                input_index: self.input_index as u64,
                output_index: self.output_index as u64,
            }
        }
    }

    impl IntoProto<JupiterRouteIxDataProto> for RouteIxData {
        fn into_proto(self) -> JupiterRouteIxDataProto {
            JupiterRouteIxDataProto {
                route_plan: self
                    .route_plan
                    .into_iter()
                    .map(IntoProto::into_proto)
                    .collect(),
                in_amount: self.in_amount,
                quoted_out_amount: self.quoted_out_amount,
                slippage_bps: self.slippage_bps as u64,
                platform_fee_bps: self.platform_fee_bps as u64,
            }
        }
    }

    impl IntoProto<JupiterSwapEventProto> for SwapEvent {
        fn into_proto(self) -> JupiterSwapEventProto {
            JupiterSwapEventProto {
                amm: self.amm.to_string(),
                input_mint: self.input_mint.to_string(),
                input_amount: self.input_amount,
                output_mint: self.output_mint.to_string(),
                output_amount: self.output_amount,
            }
        }
    }

    impl IntoProto<JupiterProgramIxProto> for JupiterProgramIx {
        fn into_proto(self) -> JupiterProgramIxProto {
            match self {
                JupiterProgramIx::Route(accounts, data) => JupiterProgramIxProto {
                    ix_oneof: Some(IxOneof::Route(JupiterRouteInstructionProto {
                        accounts: Some(accounts.into_proto()),
                        data: Some(data.into_proto()),
                    })),
                },
                JupiterProgramIx::SwapEvent(data) => JupiterProgramIxProto {
                    ix_oneof: Some(IxOneof::SwapEvent(data.into_proto())),
                },
                //Ingore others
                _ => JupiterProgramIxProto { ix_oneof: None },
            }
        }
    }

    impl ParseProto for InstructionParser {
        type Message = JupiterProgramIxProto;

        fn output_into_message(value: Self::Output) -> Self::Message {
            value.into_proto()
        }
    }
}
