syntax = "proto3";

package vixen.parser;

message PumpfunBuyAccountsProto {
    string global = 1;
    string fee_recipient = 2;
    string mint = 3;
    string bonding_curve = 4;
    string associated_bonding_curve = 5;
    string associated_user = 6;
    string user = 7;
    string system_program = 8;
    string token_program = 9;
    string rent = 10;
    string event_authority = 11;
    string program = 12;
}

message PumpfunBuyIxDataProto {
    uint64 amount = 1;
    uint64 max_sol_cost = 2;
}

message PumpfunBuyInstructionProto {
    PumpfunBuyAccountsProto accounts = 1;
    PumpfunBuyIxDataProto data = 2;
}