//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use raydium_amm_program_sdk::accounts::AmmInfo;
use raydium_amm_program_sdk::accounts::Fees;
use raydium_amm_program_sdk::accounts::TargetOrders;
use raydium_amm_program_sdk::ID;

/// RaydiumAmm Program State
#[allow(clippy::large_enum_variant)]
#[derive(Debug)]
pub enum RaydiumAmmProgramState {
    TargetOrders(TargetOrders),
    Fees(Fees),
    AmmInfo(AmmInfo),
}

impl RaydiumAmmProgramState {
    pub fn try_unpack(data_bytes: &[u8]) -> yellowstone_vixen_core::ParseResult<Self> {
        let data_len = data_bytes.len();
        const TARGETORDERS_LEN: usize = std::mem::size_of::<TargetOrders>();
        const FEES_LEN: usize = std::mem::size_of::<Fees>();
        const AMMINFO_LEN: usize = std::mem::size_of::<AmmInfo>();
        match data_len {
            TARGETORDERS_LEN => Ok(RaydiumAmmProgramState::TargetOrders(
                TargetOrders::from_bytes(data_bytes)?,
            )),
            FEES_LEN => Ok(RaydiumAmmProgramState::Fees(Fees::from_bytes(data_bytes)?)),
            AMMINFO_LEN => Ok(RaydiumAmmProgramState::AmmInfo(AmmInfo::from_bytes(
                data_bytes,
            )?)),
            _ => Err(yellowstone_vixen_core::ParseError::from(
                "Invalid Account data length".to_owned(),
            )),
        }
    }
}

#[derive(Debug, Copy, Clone)]
pub struct AccountParser;

impl yellowstone_vixen_core::Parser for AccountParser {
    type Input = yellowstone_vixen_core::AccountUpdate;
    type Output = RaydiumAmmProgramState;

    fn id(&self) -> std::borrow::Cow<str> {
        "raydium_amm::AccountParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .account_owners([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        acct: &yellowstone_vixen_core::AccountUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        let inner = acct
            .account
            .as_ref()
            .ok_or(solana_program::program_error::ProgramError::InvalidArgument)?;
        RaydiumAmmProgramState::try_unpack(&inner.data)
    }
}

impl yellowstone_vixen_core::ProgramParser for AccountParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

#[cfg(feature = "proto")]
mod proto_parser {
    use yellowstone_vixen_core::proto::ParseProto;
    use yellowstone_vixen_proto::parser::{
        raydium_amm_program_state_proto, RaydiumAmmProgramStateProto, TargetOrderProto,
        TargetOrdersProto,
    };

    use super::{AccountParser, RaydiumAmmProgramState, TargetOrders};
    use crate::helpers::IntoProto;
    use raydium_amm_program_sdk::types::TargetOrder;

    impl IntoProto<TargetOrderProto> for TargetOrder {
        fn into_proto(self) -> TargetOrderProto {
            TargetOrderProto {
                price: self.price.to_string(),
                vol: self.vol.to_string(),
            }
        }
    }

    impl IntoProto<TargetOrdersProto> for TargetOrders {
        fn into_proto(self) -> TargetOrdersProto {
            TargetOrdersProto {
                discriminator: self.discriminator.to_vec(),
                owner: self.owner.to_vec(),
                buy_orders: self
                    .buy_orders
                    .into_iter()
                    .map(IntoProto::into_proto)
                    .collect(),
                padding1: self.padding1.to_vec(),
                target_x: self.target_x.to_string(),
                target_y: self.target_y.to_string(),
                plan_x_buy: self.plan_x_buy.to_string(),
                plan_y_buy: self.plan_y_buy.to_string(),
                plan_x_sell: self.plan_x_sell.to_string(),
                plan_y_sell: self.plan_y_sell.to_string(),
                placed_x: self.placed_x.to_string(),
                placed_y: self.placed_y.to_string(),
                calc_pnl_x: self.calc_pnl_x.to_string(),
                calc_pnl_y: self.calc_pnl_y.to_string(),
                sell_orders: self
                    .sell_orders
                    .into_iter()
                    .map(IntoProto::into_proto)
                    .collect(),
                padding2: self.padding2.to_vec(),
                replace_buy_client_id: self.replace_buy_client_id.to_vec(),
                replace_sell_client_id: self.replace_sell_client_id.to_vec(),
                last_order_numerator: self.last_order_numerator,
                last_order_denominator: self.last_order_denominator,
                plan_orders_cur: self.plan_orders_cur,
                place_orders_cur: self.place_orders_cur,
                valid_buy_order_num: self.valid_buy_order_num,
                valid_sell_order_num: self.valid_sell_order_num,
                padding3: self.padding3.to_vec(),
                free_slot_bits: self.free_slot_bits.to_string(),
            }
        }
    }

    impl ParseProto for AccountParser {
        type Message = RaydiumAmmProgramStateProto;

        fn output_into_message(value: Self::Output) -> Self::Message {
            let state_oneof = match value {
                RaydiumAmmProgramState::TargetOrders(data) => Some(
                    raydium_amm_program_state_proto::StateOneof::TargetOrders(data.into_proto()),
                ),
                _ => None,
            };
            Self::Message { state_oneof }
        }
    }
}
