//! This code was AUTOGENERATED using the codama library.
//! Please DO NOT EDIT THIS FILE, instead use visitors
//! to add features, then rerun codama to update it.
//!
//! <https://github.com/codama-idl/codama>
//!

use borsh::BorshDeserialize;
use raydium_amm_program_sdk::instructions::{
    AdminCancelOrders as AdminCancelOrdersIxAccounts,
    AdminCancelOrdersInstructionArgs as AdminCancelOrdersIxData,
    CreateConfigAccount as CreateConfigAccountIxAccounts, Deposit as DepositIxAccounts,
    DepositInstructionArgs as DepositIxData, Initialize as InitializeIxAccounts,
    Initialize2 as Initialize2IxAccounts, Initialize2InstructionArgs as Initialize2IxData,
    InitializeInstructionArgs as InitializeIxData,
    MigrateToOpenBook as MigrateToOpenBookIxAccounts, MonitorStep as MonitorStepIxAccounts,
    MonitorStepInstructionArgs as MonitorStepIxData, PreInitialize as PreInitializeIxAccounts,
    PreInitializeInstructionArgs as PreInitializeIxData, SetParams as SetParamsIxAccounts,
    SetParamsInstructionArgs as SetParamsIxData, SimulateInfo as SimulateInfoIxAccounts,
    SimulateInfoInstructionArgs as SimulateInfoIxData, SwapBaseIn as SwapBaseInIxAccounts,
    SwapBaseInInstructionArgs as SwapBaseInIxData, SwapBaseOut as SwapBaseOutIxAccounts,
    SwapBaseOutInstructionArgs as SwapBaseOutIxData,
    UpdateConfigAccount as UpdateConfigAccountIxAccounts,
    UpdateConfigAccountInstructionArgs as UpdateConfigAccountIxData,
    Withdraw as WithdrawIxAccounts, WithdrawInstructionArgs as WithdrawIxData,
    WithdrawPnl as WithdrawPnlIxAccounts, WithdrawSrm as WithdrawSrmIxAccounts,
    WithdrawSrmInstructionArgs as WithdrawSrmIxData,
};
use raydium_amm_program_sdk::ID;
use solana_program::pubkey;

use solana_program::pubkey::Pubkey;

/// RaydiumAmm Instructions
#[derive(Debug)]
pub enum RaydiumAmmProgramIx {
    Initialize(InitializeIxAccounts, InitializeIxData),
    Initialize2(Initialize2IxAccounts, Initialize2IxData),
    MonitorStep(MonitorStepIxAccounts, MonitorStepIxData),
    Deposit(DepositIxAccounts, DepositIxData),
    Withdraw(WithdrawIxAccounts, WithdrawIxData),
    MigrateToOpenBook(MigrateToOpenBookIxAccounts),
    SetParams(SetParamsIxAccounts, SetParamsIxData),
    WithdrawPnl(WithdrawPnlIxAccounts),
    WithdrawSrm(WithdrawSrmIxAccounts, WithdrawSrmIxData),
    SwapBaseIn(SwapBaseInIxAccounts, SwapBaseInIxData),
    PreInitialize(PreInitializeIxAccounts, PreInitializeIxData),
    SwapBaseOut(SwapBaseOutIxAccounts, SwapBaseOutIxData),
    SimulateInfo(SimulateInfoIxAccounts, SimulateInfoIxData),
    AdminCancelOrders(AdminCancelOrdersIxAccounts, AdminCancelOrdersIxData),
    CreateConfigAccount(CreateConfigAccountIxAccounts),
    UpdateConfigAccount(UpdateConfigAccountIxAccounts, UpdateConfigAccountIxData),
}

#[derive(Debug, Copy, Clone)]
pub struct InstructionParser;

impl yellowstone_vixen_core::Parser for InstructionParser {
    type Input = yellowstone_vixen_core::instruction::InstructionUpdate;
    type Output = RaydiumAmmProgramIx;

    fn id(&self) -> std::borrow::Cow<str> {
        "RaydiumAmm::InstructionParser".into()
    }

    fn prefilter(&self) -> yellowstone_vixen_core::Prefilter {
        yellowstone_vixen_core::Prefilter::builder()
            .transaction_accounts([ID])
            .build()
            .unwrap()
    }

    async fn parse(
        &self,
        ix_update: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<Self::Output> {
        if ix_update.program.equals_ref(ID) {
            InstructionParser::parse_impl(ix_update)
        } else {
            Err(yellowstone_vixen_core::ParseError::Filtered)
        }
    }
}

impl yellowstone_vixen_core::ProgramParser for InstructionParser {
    #[inline]
    fn program_id(&self) -> yellowstone_vixen_core::Pubkey {
        ID.to_bytes().into()
    }
}

impl InstructionParser {
    pub(crate) fn parse_impl(
        ix: &yellowstone_vixen_core::instruction::InstructionUpdate,
    ) -> yellowstone_vixen_core::ParseResult<RaydiumAmmProgramIx> {
        let accounts_len = ix.accounts.len();
        let ix_discriminator: [u8; 1] = ix.data[0..1].try_into()?;
        let mut ix_data = &ix.data[1..];
        match ix_discriminator {
            [0] => {
                check_min_accounts_req(accounts_len, 18)?;
                let ix_accounts = InitializeIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    system_program: ix.accounts[1].0.into(),
                    rent: ix.accounts[2].0.into(),
                    amm: ix.accounts[3].0.into(),
                    amm_authority: ix.accounts[4].0.into(),
                    amm_open_orders: ix.accounts[5].0.into(),
                    lp_mint_address: ix.accounts[6].0.into(),
                    coin_mint_address: ix.accounts[7].0.into(),
                    pc_mint_address: ix.accounts[8].0.into(),
                    pool_coin_token_account: ix.accounts[9].0.into(),
                    pool_pc_token_account: ix.accounts[10].0.into(),
                    pool_withdraw_queue: ix.accounts[11].0.into(),
                    pool_target_orders_account: ix.accounts[12].0.into(),
                    user_lp_token_account: ix.accounts[13].0.into(),
                    pool_temp_lp_token_account: ix.accounts[14].0.into(),
                    serum_program: ix.accounts[15].0.into(),
                    serum_market: ix.accounts[16].0.into(),
                    user_wallet: ix.accounts[17].0.into(),
                };
                let de_ix_data: InitializeIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::Initialize(ix_accounts, de_ix_data))
            },
            [1] => {
                check_min_accounts_req(accounts_len, 21)?;
                let ix_accounts = Initialize2IxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    spl_associated_token_account: ix.accounts[1].0.into(),
                    system_program: ix.accounts[2].0.into(),
                    rent: ix.accounts[3].0.into(),
                    amm: ix.accounts[4].0.into(),
                    amm_authority: ix.accounts[5].0.into(),
                    amm_open_orders: ix.accounts[6].0.into(),
                    lp_mint: ix.accounts[7].0.into(),
                    coin_mint: ix.accounts[8].0.into(),
                    pc_mint: ix.accounts[9].0.into(),
                    pool_coin_token_account: ix.accounts[10].0.into(),
                    pool_pc_token_account: ix.accounts[11].0.into(),
                    pool_withdraw_queue: ix.accounts[12].0.into(),
                    amm_target_orders: ix.accounts[13].0.into(),
                    pool_temp_lp: ix.accounts[14].0.into(),
                    serum_program: ix.accounts[15].0.into(),
                    serum_market: ix.accounts[16].0.into(),
                    user_wallet: ix.accounts[17].0.into(),
                    user_token_coin: ix.accounts[18].0.into(),
                    user_token_pc: ix.accounts[19].0.into(),
                    user_lp_token_account: ix.accounts[20].0.into(),
                };
                let de_ix_data: Initialize2IxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::Initialize2(ix_accounts, de_ix_data))
            },
            [2] => {
                check_min_accounts_req(accounts_len, 19)?;
                let ix_accounts = MonitorStepIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    rent: ix.accounts[1].0.into(),
                    clock: ix.accounts[2].0.into(),
                    amm: ix.accounts[3].0.into(),
                    amm_authority: ix.accounts[4].0.into(),
                    amm_open_orders: ix.accounts[5].0.into(),
                    amm_target_orders: ix.accounts[6].0.into(),
                    pool_coin_token_account: ix.accounts[7].0.into(),
                    pool_pc_token_account: ix.accounts[8].0.into(),
                    pool_withdraw_queue: ix.accounts[9].0.into(),
                    serum_program: ix.accounts[10].0.into(),
                    serum_market: ix.accounts[11].0.into(),
                    serum_coin_vault_account: ix.accounts[12].0.into(),
                    serum_pc_vault_account: ix.accounts[13].0.into(),
                    serum_vault_signer: ix.accounts[14].0.into(),
                    serum_req_q: ix.accounts[15].0.into(),
                    serum_event_q: ix.accounts[16].0.into(),
                    serum_bids: ix.accounts[17].0.into(),
                    serum_asks: ix.accounts[18].0.into(),
                };
                let de_ix_data: MonitorStepIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::MonitorStep(ix_accounts, de_ix_data))
            },
            [3] => {
                check_min_accounts_req(accounts_len, 14)?;
                let ix_accounts = DepositIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: ix.accounts[4].0.into(),
                    lp_mint_address: ix.accounts[5].0.into(),
                    pool_coin_token_account: ix.accounts[6].0.into(),
                    pool_pc_token_account: ix.accounts[7].0.into(),
                    serum_market: ix.accounts[8].0.into(),
                    user_coin_token_account: ix.accounts[9].0.into(),
                    user_pc_token_account: ix.accounts[10].0.into(),
                    user_lp_token_account: ix.accounts[11].0.into(),
                    user_owner: ix.accounts[12].0.into(),
                    serum_event_queue: ix.accounts[13].0.into(),
                };
                let de_ix_data: DepositIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::Deposit(ix_accounts, de_ix_data))
            },
            [4] => {
                check_min_accounts_req(accounts_len, 22)?;
                let ix_accounts = WithdrawIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: ix.accounts[4].0.into(),
                    lp_mint_address: ix.accounts[5].0.into(),
                    pool_coin_token_account: ix.accounts[6].0.into(),
                    pool_pc_token_account: ix.accounts[7].0.into(),
                    pool_withdraw_queue: ix.accounts[8].0.into(),
                    pool_temp_lp_token_account: ix.accounts[9].0.into(),
                    serum_program: ix.accounts[10].0.into(),
                    serum_market: ix.accounts[11].0.into(),
                    serum_coin_vault_account: ix.accounts[12].0.into(),
                    serum_pc_vault_account: ix.accounts[13].0.into(),
                    serum_vault_signer: ix.accounts[14].0.into(),
                    user_lp_token_account: ix.accounts[15].0.into(),
                    uer_coin_token_account: ix.accounts[16].0.into(),
                    uer_pc_token_account: ix.accounts[17].0.into(),
                    user_owner: ix.accounts[18].0.into(),
                    serum_event_q: ix.accounts[19].0.into(),
                    serum_bids: ix.accounts[20].0.into(),
                    serum_asks: ix.accounts[21].0.into(),
                };
                let de_ix_data: WithdrawIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::Withdraw(ix_accounts, de_ix_data))
            },
            [5] => {
                check_min_accounts_req(accounts_len, 21)?;
                let ix_accounts = MigrateToOpenBookIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    system_program: ix.accounts[1].0.into(),
                    rent: ix.accounts[2].0.into(),
                    amm: ix.accounts[3].0.into(),
                    amm_authority: ix.accounts[4].0.into(),
                    amm_open_orders: ix.accounts[5].0.into(),
                    amm_token_coin: ix.accounts[6].0.into(),
                    amm_token_pc: ix.accounts[7].0.into(),
                    amm_target_orders: ix.accounts[8].0.into(),
                    serum_program: ix.accounts[9].0.into(),
                    serum_market: ix.accounts[10].0.into(),
                    serum_bids: ix.accounts[11].0.into(),
                    serum_asks: ix.accounts[12].0.into(),
                    serum_event_queue: ix.accounts[13].0.into(),
                    serum_coin_vault: ix.accounts[14].0.into(),
                    serum_pc_vault: ix.accounts[15].0.into(),
                    serum_vault_signer: ix.accounts[16].0.into(),
                    new_amm_open_orders: ix.accounts[17].0.into(),
                    new_serum_program: ix.accounts[18].0.into(),
                    new_serum_market: ix.accounts[19].0.into(),
                    admin: ix.accounts[20].0.into(),
                };
                Ok(RaydiumAmmProgramIx::MigrateToOpenBook(ix_accounts))
            },
            [6] => {
                check_min_accounts_req(accounts_len, 16)?;
                let ix_accounts = SetParamsIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: ix.accounts[4].0.into(),
                    amm_coin_vault: ix.accounts[5].0.into(),
                    amm_pc_vault: ix.accounts[6].0.into(),
                    serum_program: ix.accounts[7].0.into(),
                    serum_market: ix.accounts[8].0.into(),
                    serum_coin_vault: ix.accounts[9].0.into(),
                    serum_pc_vault: ix.accounts[10].0.into(),
                    serum_vault_signer: ix.accounts[11].0.into(),
                    serum_event_queue: ix.accounts[12].0.into(),
                    serum_bids: ix.accounts[13].0.into(),
                    serum_asks: ix.accounts[14].0.into(),
                    amm_admin_account: ix.accounts[15].0.into(),
                };
                let de_ix_data: SetParamsIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::SetParams(ix_accounts, de_ix_data))
            },
            [7] => {
                check_min_accounts_req(accounts_len, 17)?;
                let ix_accounts = WithdrawPnlIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_config: ix.accounts[2].0.into(),
                    amm_authority: ix.accounts[3].0.into(),
                    amm_open_orders: ix.accounts[4].0.into(),
                    pool_coin_token_account: ix.accounts[5].0.into(),
                    pool_pc_token_account: ix.accounts[6].0.into(),
                    coin_pnl_token_account: ix.accounts[7].0.into(),
                    pc_pnl_token_account: ix.accounts[8].0.into(),
                    pnl_owner_account: ix.accounts[9].0.into(),
                    amm_target_orders: ix.accounts[10].0.into(),
                    serum_program: ix.accounts[11].0.into(),
                    serum_market: ix.accounts[12].0.into(),
                    serum_event_queue: ix.accounts[13].0.into(),
                    serum_coin_vault_account: ix.accounts[14].0.into(),
                    serum_pc_vault_account: ix.accounts[15].0.into(),
                    serum_vault_signer: ix.accounts[16].0.into(),
                };
                Ok(RaydiumAmmProgramIx::WithdrawPnl(ix_accounts))
            },
            [8] => {
                check_min_accounts_req(accounts_len, 6)?;
                let ix_accounts = WithdrawSrmIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_owner_account: ix.accounts[2].0.into(),
                    amm_authority: ix.accounts[3].0.into(),
                    srm_token: ix.accounts[4].0.into(),
                    dest_srm_token: ix.accounts[5].0.into(),
                };
                let de_ix_data: WithdrawSrmIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::WithdrawSrm(ix_accounts, de_ix_data))
            },
            [9] => {
                check_min_accounts_req(accounts_len, 18)?;
                let ix_accounts = SwapBaseInIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: Some(Pubkey::new_from_array(ix.accounts[4].0)).into(),
                    pool_coin_token_account: ix.accounts[5].0.into(),
                    pool_pc_token_account: ix.accounts[6].0.into(),
                    serum_program: ix.accounts[7].0.into(),
                    serum_market: ix.accounts[8].0.into(),
                    serum_bids: ix.accounts[9].0.into(),
                    serum_asks: ix.accounts[10].0.into(),
                    serum_event_queue: ix.accounts[11].0.into(),
                    serum_coin_vault_account: ix.accounts[12].0.into(),
                    serum_pc_vault_account: ix.accounts[13].0.into(),
                    serum_vault_signer: ix.accounts[14].0.into(),
                    user_source_token_account: ix.accounts[15].0.into(),
                    user_destination_token_account: ix.accounts[16].0.into(),
                    user_source_owner: ix.accounts[17].0.into(),
                };
                let de_ix_data: SwapBaseInIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::SwapBaseIn(ix_accounts, de_ix_data))
            },
            [10] => {
                check_min_accounts_req(accounts_len, 14)?;
                let ix_accounts = PreInitializeIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    system_program: ix.accounts[1].0.into(),
                    rent: ix.accounts[2].0.into(),
                    amm_target_orders: ix.accounts[3].0.into(),
                    pool_withdraw_queue: ix.accounts[4].0.into(),
                    amm_authority: ix.accounts[5].0.into(),
                    lp_mint_address: ix.accounts[6].0.into(),
                    coin_mint_address: ix.accounts[7].0.into(),
                    pc_mint_address: ix.accounts[8].0.into(),
                    pool_coin_token_account: ix.accounts[9].0.into(),
                    pool_pc_token_account: ix.accounts[10].0.into(),
                    pool_temp_lp_token_account: ix.accounts[11].0.into(),
                    serum_market: ix.accounts[12].0.into(),
                    user_wallet: ix.accounts[13].0.into(),
                };
                let de_ix_data: PreInitializeIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::PreInitialize(ix_accounts, de_ix_data))
            },
            [11] => {
                check_min_accounts_req(accounts_len, 18)?;
                let ix_accounts = SwapBaseOutIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: Some(Pubkey::new_from_array(ix.accounts[4].0)).into(),
                    pool_coin_token_account: ix.accounts[5].0.into(),
                    pool_pc_token_account: ix.accounts[6].0.into(),
                    serum_program: ix.accounts[7].0.into(),
                    serum_market: ix.accounts[8].0.into(),
                    serum_bids: ix.accounts[9].0.into(),
                    serum_asks: ix.accounts[10].0.into(),
                    serum_event_queue: ix.accounts[11].0.into(),
                    serum_coin_vault_account: ix.accounts[12].0.into(),
                    serum_pc_vault_account: ix.accounts[13].0.into(),
                    serum_vault_signer: ix.accounts[14].0.into(),
                    user_source_token_account: ix.accounts[15].0.into(),
                    user_destination_token_account: ix.accounts[16].0.into(),
                    user_source_owner: ix.accounts[17].0.into(),
                };
                let de_ix_data: SwapBaseOutIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::SwapBaseOut(ix_accounts, de_ix_data))
            },
            [12] => {
                check_min_accounts_req(accounts_len, 8)?;
                let ix_accounts = SimulateInfoIxAccounts {
                    amm: ix.accounts[0].0.into(),
                    amm_authority: ix.accounts[1].0.into(),
                    amm_open_orders: ix.accounts[2].0.into(),
                    pool_coin_token_account: ix.accounts[3].0.into(),
                    pool_pc_token_account: ix.accounts[4].0.into(),
                    lp_mint_address: ix.accounts[5].0.into(),
                    serum_market: ix.accounts[6].0.into(),
                    serum_event_queue: ix.accounts[7].0.into(),
                };
                let de_ix_data: SimulateInfoIxData = BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::SimulateInfo(ix_accounts, de_ix_data))
            },
            [13] => {
                check_min_accounts_req(accounts_len, 17)?;
                let ix_accounts = AdminCancelOrdersIxAccounts {
                    token_program: ix.accounts[0].0.into(),
                    amm: ix.accounts[1].0.into(),
                    amm_authority: ix.accounts[2].0.into(),
                    amm_open_orders: ix.accounts[3].0.into(),
                    amm_target_orders: ix.accounts[4].0.into(),
                    pool_coin_token_account: ix.accounts[5].0.into(),
                    pool_pc_token_account: ix.accounts[6].0.into(),
                    amm_owner_account: ix.accounts[7].0.into(),
                    amm_config: ix.accounts[8].0.into(),
                    serum_program: ix.accounts[9].0.into(),
                    serum_market: ix.accounts[10].0.into(),
                    serum_coin_vault_account: ix.accounts[11].0.into(),
                    serum_pc_vault_account: ix.accounts[12].0.into(),
                    serum_vault_signer: ix.accounts[13].0.into(),
                    serum_event_q: ix.accounts[14].0.into(),
                    serum_bids: ix.accounts[15].0.into(),
                    serum_asks: ix.accounts[16].0.into(),
                };
                let de_ix_data: AdminCancelOrdersIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::AdminCancelOrders(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            [14] => {
                check_min_accounts_req(accounts_len, 5)?;
                let ix_accounts = CreateConfigAccountIxAccounts {
                    admin: ix.accounts[0].0.into(),
                    amm_config: ix.accounts[1].0.into(),
                    owner: ix.accounts[2].0.into(),
                    system_program: ix.accounts[3].0.into(),
                    rent: ix.accounts[4].0.into(),
                };
                Ok(RaydiumAmmProgramIx::CreateConfigAccount(ix_accounts))
            },
            [15] => {
                check_min_accounts_req(accounts_len, 2)?;
                let ix_accounts = UpdateConfigAccountIxAccounts {
                    admin: ix.accounts[0].0.into(),
                    amm_config: ix.accounts[1].0.into(),
                };
                let de_ix_data: UpdateConfigAccountIxData =
                    BorshDeserialize::deserialize(&mut ix_data)?;
                Ok(RaydiumAmmProgramIx::UpdateConfigAccount(
                    ix_accounts,
                    de_ix_data,
                ))
            },
            _ => Err(yellowstone_vixen_core::ParseError::from(
                "Invalid Instruction discriminator".to_owned(),
            )),
        }
    }
}

pub fn check_min_accounts_req(
    actual: usize,
    expected: usize,
) -> yellowstone_vixen_core::ParseResult<()> {
    if actual < expected {
        Err(yellowstone_vixen_core::ParseError::from(format!(
            "Too few accounts provided: expected {expected}, got {actual}"
        )))
    } else {
        Ok(())
    }
}

#[cfg(feature = "proto")]
mod proto_parser {
    use raydium_amm_program_sdk::ID;
    use yellowstone_vixen_core::proto::ParseProto;
    use yellowstone_vixen_proto::parser::{
        raydium_amm_program_ix_proto::IxOneof, RaydiumAmmProgramIxProto,
        RaydiumAmmSwapBaseInAccountsProto, RaydiumAmmSwapBaseInInstructionProto,
        RaydiumAmmSwapBaseInIxDataProto,
    };

    use super::{InstructionParser, RaydiumAmmProgramIx, SwapBaseInIxAccounts, SwapBaseInIxData};
    use crate::helpers::IntoProto;

    impl ParseProto for InstructionParser {
        type Message = RaydiumAmmProgramIxProto;

        fn output_into_message(value: Self::Output) -> Self::Message {
            value.into_proto()
        }
    }

    impl IntoProto<RaydiumAmmSwapBaseInAccountsProto> for SwapBaseInIxAccounts {
        fn into_proto(self) -> RaydiumAmmSwapBaseInAccountsProto {
            RaydiumAmmSwapBaseInAccountsProto {
                token_program: self.token_program.to_string(),
                amm: self.amm.to_string(),
                amm_authority: self.amm_authority.to_string(),
                amm_open_orders: self.amm_open_orders.to_string(),
                amm_target_orders: self.amm_target_orders.unwrap_or(ID).to_string(),
                pool_coin_token_account: self.pool_coin_token_account.to_string(),
                pool_pc_token_account: self.pool_pc_token_account.to_string(),
                serum_program: self.serum_program.to_string(),
                serum_market: self.serum_market.to_string(),
                serum_bids: self.serum_bids.to_string(),
                serum_asks: self.serum_asks.to_string(),
                serum_event_queue: self.serum_event_queue.to_string(),
                serum_coin_vault_account: self.serum_coin_vault_account.to_string(),
                serum_pc_vault_account: self.serum_pc_vault_account.to_string(),
                serum_vault_signer: self.serum_vault_signer.to_string(),
                user_source_token_account: self.user_source_token_account.to_string(),
                user_destination_token_account: self.user_destination_token_account.to_string(),
                user_source_owner: self.user_source_owner.to_string(),
            }
        }
    }

    impl IntoProto<RaydiumAmmSwapBaseInIxDataProto> for SwapBaseInIxData {
        fn into_proto(self) -> RaydiumAmmSwapBaseInIxDataProto {
            RaydiumAmmSwapBaseInIxDataProto {
                amount_in: self.amount_in,
                minimum_amount_out: self.minimum_amount_out,
            }
        }
    }

    impl IntoProto<RaydiumAmmProgramIxProto> for RaydiumAmmProgramIx {
        fn into_proto(self) -> RaydiumAmmProgramIxProto {
            match self {
                RaydiumAmmProgramIx::SwapBaseIn(accounts, data) => RaydiumAmmProgramIxProto {
                    ix_oneof: Some(IxOneof::SwapBaseIn(RaydiumAmmSwapBaseInInstructionProto {
                        accounts: Some(accounts.into_proto()),
                        data: Some(data.into_proto()),
                    })),
                },
                //Ingore others
                _ => RaydiumAmmProgramIxProto { ix_oneof: None },
            }
        }
    }
}
